//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQLInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySQLInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 #代码开始  
        ///[Client]  
        ///#设置3306端口  
        ///port = {mysqlport}
        ///[mysqld]  
        ///#设置3306端口  
        ///port = {mysqlport}  
        ///# 设置mysql的安装目录  
        ///basedir={mysqldatadir}
        ///# 设置mysql数据库的数据的存放目录  
        ///datadir={mysqldatadir}
        ///# 允许最大连接数  
        ///max_connections=500  
        ///# 服务端使用的字符集默认为8比特编码的latin1字符集  
        ///character-set-server=utf8  
        ///# 创建新表时将使用的默认存储引擎  
        ///default-storage-engine=INNODB
        ///sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES  
        ///
        ///max_allowed_packet=100M
        ///
        ///[mysql]  
        ///# 设置mysql客户端默认字符集  
        ///default-character-set=utf8  
        ///#代码结束
        /// 的本地化字符串。
        /// </summary>
        internal static string my {
            get {
                return ResourceManager.GetString("my", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] MySql5_7_16 {
            get {
                object obj = ResourceManager.GetObject("MySql5_7_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 /*
        ///SQLyog ��ҵ�� - MySQL GUI v8.14 
        ///MySQL - 5.7.36 : Database - zixingtest
        ///*********************************************************************
        ///*/
        ///
        ///
        ////*!40101 SET NAMES utf8 */;
        ///
        ////*!40101 SET SQL_MODE=&apos;&apos;*/;
        ///
        ////*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
        ////*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
        ////*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE=&apos;NO_AUTO_VALUE_ON_ZERO&apos; */;
        ////*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
        ///CREA [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string zixingtest {
            get {
                return ResourceManager.GetString("zixingtest", resourceCulture);
            }
        }
    }
}
